# Generated by Django 5.1.2 on 2024-10-27 08:44

import django.core.validators
import furryFunnies.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(4), furryFunnies.validators.name_validator], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), furryFunnies.validators.name_validator], verbose_name='Last Name')),
                ('passcode', models.CharField(error_messages={'max_length': 'Your passcode must be exactly 6 digits!'}, help_text='Your passcode must be a combination of 6 digits', max_length=6, validators=[django.core.validators.MinLengthValidator(6, 'Your passcode must be exactly 6 digits!')])),
                ('pets_number', models.PositiveSmallIntegerField()),
                ('info', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
