# Generated by Django 5.1.2 on 2024-10-27 10:29

import django.core.validators
import furryFunnies.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Profile Image URL'),
        ),
        migrations.AlterField(
            model_name='author',
            name='passcode',
            field=models.CharField(help_text='Your passcode must be a combination of 6 digits', max_length=6, validators=[django.core.validators.MinLengthValidator(6, 'Your passcode must be exactly 6 digits!'), furryFunnies.validators.only_digits_validator]),
        ),
        migrations.AlterField(
            model_name='author',
            name='pets_number',
            field=models.PositiveSmallIntegerField(verbose_name='Pets Number'),
        ),
    ]
